export const GlobalStateKeyAkitaDAO = 'akita_dao'
export const GlobalStateKeyAkitaEscrow = 'akita_escrow'
export const GlobalStateKeyVersion = 'version'
export const GlobalStateKeyChildContractVersion = 'child_contract_version'
export const GlobalStateKeyRevocationApp = 'revocation_app'
