export const SubscriptionsBoxPrefixSubscriptions = 's'
export const SubscriptionsBoxPrefixSubscriptionsList = 'l'
export const SubscriptionsBoxPrefixServices = 'o'
export const SubscriptionsBoxPrefixServicesList = 'm'
export const SubscriptionsBoxPrefixBlocks = 'b'
export const SubscriptionsBoxPrefixPasses = 'p'