export const ERR_ONLY_CREATOR_CAN_REKEY = 'only the creator can rekey a spend contract'
export const ERR_INVALID_PAYMENT = 'invalid payment'
export const ERR_ONLY_APPS = 'Only applications can create spending accounts'
export const ERR_FORBIDDEN = 'only the creator wallet can delete a spending account'
export const ERR_ONLY_WALLET_OR_PLUGIN = 'Only the wallet or plugin can opt in'
export const ERR_ONLY_FACTORY_CAN_DELETE = 'Only the factory can delete the application'
