export const AkitaDAOGlobalStateKeys = {
    status: 'status',
    version: 'version',
    contentPolicy: 'content_policy',
    minimumRewardsImpact: 'minimum_rewards_impact',
    appList: 'app_list',
    socialFees: 'social_fees',
    stakingFees: 'staking_fees',
    subscriptionFees: 'subscription_fees',
    nftFees: 'nft_fees',
    krbyPercentage: 'krby_percentage',
    moderatorPercentage: 'mod_percentage',
    akitaAssets: 'akita_assets',
    proposalSettings: 'proposal_settings',
    revocationAddress: 'revocation_address',
    proposalID: 'proposal_id',
    disbursementCursor: 'disbursement_cursor',
}