export const errs = {
    PLUGIN_DOES_NOT_EXIST: 'Plugin does not exist',
    PLUGIN_EXPIRED: 'Plugin has expired',
    PLUGIN_ON_COOLDOWN: 'Plugin is on cooldown',
    METHOD_NOT_ALLOWED: 'Method not allowed',
    INVALID_EXECUTION_KEY: 'Invalid execution key',
    DOES_NOT_REKEY_BACK: 'Does not rekey back',
    NO_METHOD_SIGNATURE: 'No method signature provided',
    INVALID_METHOD_SIGNATURE_LENGTH: 'Invalid method signature length',
    KEY_REGISTRATION_NOT_SUPPORTED: 'Key registration not supported',
    METADATA_HASH_TOO_LONG: 'Metadata hash is too long',
    UNKNOWN_TRANSACTION_TYPE: 'Unknown transaction type',
    ALREADY_INITIALIZED: 'Already initialized',
    VERSION_CANNOT_BE_EMPTY: 'Version cannot be empty',
    PLUGIN_DOES_NOT_CONTROL_WALLET: 'This plugin is not in control of the account',
    DISBURSEMENT_DOES_NOT_EXIST: 'Disbursement does not exist',
    DISBURSEMENT_LOCKED: 'Disbursement is still locked',
    DISBURSEMENT_FULLY_DISTRIBUTED: 'Disbursement is fully distributed',
    ALLOCATION_DOES_NOT_EXIST: 'Allocation does not exist',
    UNKNOWN_DISBURSEMENT_TYPE: 'Unknown disbursement type',
    TIME_NOT_FAR_ENOUGH_IN_THE_FUTURE: 'Time is not far enough in the future, must be at least 60 seconds from now',
    TOKEN_ALLOCATION_BOX_DOES_NOT_EXIST: 'Token allocation box does not exist',
    TOKEN_ALLOCATION_BOX_ALREADY_EXISTS: 'Token allocation box already exists',
    INSUFFICIENT_AKITA: 'Insufficient Akita',
    INVALID_RECEIVE_PAYMENT: 'Invalid receive payment',
};