export const ERR_NOT_AKITA_DAO = 'Only the Akita DAO can call this function'
export const ERR_PRICE_TOO_LOW = 'Lowest price is 4 units for divisibility'
export const ERR_MARKETPLACE_NOT_OPTED_INTO_PAYMENT_ASSET = 'Marketplace must be opted into payment asset'
export const ERR_NOT_A_LISTING = 'Not a listing contract'

export const ERR_MUST_BE_CALLED_FROM_FACTORY = 'must be called from the factory'
export const ERR_INVALID_EXPIRATION = 'invalid expiration'
export const ERR_PAYMENT_ASSET_MUST_BE_ALGO = 'payment asset must be algo'
export const ERR_PAYMENT_ASSET_MUST_NOT_BE_ALGO = 'payment asset must not be algo'
export const ERR_LISTING_EXPIRED = 'listing expired'
export const ERR_ONLY_SELLER_CAN_DELIST = 'only the seller can delist'
export const ERR_FAILED_GATE = 'gate check failed'
export const ERR_RESERVED_FOR_DIFFERENT_ADDRESS = 'reserved for different address'
export const ERR_MUST_BE_SELLER = 'must be the seller'