export const ERR_RECEIVE_ESCROW_DOES_NOT_EXIST = 'Receive escrow does not exist'
export const ERR_ESCROW_NOT_ALLOWED_TO_OPTIN = 'Escrow is not allowed to opt-in'
export const ERR_SPLITS_CANNOT_BE_EMPTY = 'Splits cannot be empty'
export const ERR_SPLITS_CANNOT_BE_MORE_THAN_10 = 'Splits cannot be more than 10'

export const ERR_SPLIT_VALUE_MUST_BE_POSITIVE_OR_REMAINDER = 'Split value must be positive or remainder'
export const ERR_SPLITS_OR_REF_REQUIRED = 'Either splits or a split reference must be provided'
export const ERR_SPLIT_REF_NOT_FOUND = 'Referenced splits not found in target contract'
export const ERR_REMAINDER_MUST_BE_LAST = 'Remainder split must be the last split'
export const ERR_ONLY_ONE_REMAINDER_ALLOWED = 'Only one remainder split is allowed'
export const ERR_PERCENTAGE_EXCEEDS_100 = 'Total percentage splits exceed 100%'
export const ERR_PERCENTAGE_MUST_BE_NOT_BE_100_WITH_REMAINDER = 'Percentage splits cannot total 100% when using a remainder'
export const ERR_FLAT_WITH_PERCENTAGE_REQUIRES_REMAINDER = 'Flat amounts with percentages require a remainder or 100% total'
export const ERR_SPLITS_MUST_TOTAL_100_OR_HAVE_REMAINDER = 'Percentage splits must total 100% or include a remainder'

export const ERR_ESCROW_NOT_IDLE = 'Escrow is not in idle phase'
export const ERR_ESCROW_NOT_ALLOCATABLE = 'Escrow is not allocatable'
export const ERR_ESCROW_NOT_READY_FOR_DISBURSEMENT = 'Escrow is not ready for disbursement'
export const ERR_ESCROW_NOT_IN_ALLOCATION_PHASE = 'Escrow is not in allocation phase'
export const ERR_ESCROW_NOT_IN_FINALIZATION_PHASE = 'Escrow is not in finalization phase'
export const ERR_ASSET_NOT_ALLOCATED = 'Asset was not allocated'
export const ERR_ASSET_ALREADY_ALLOCATED = 'Asset is already allocated'
export const ERR_ESCROW_NOT_OPTED_IN = 'Escrow is not opted in to the asset'

export const ERR_INVALID_SPLIT_TYPE = 'Invalid split type'
export const ERR_OVER_ALLOCATION = 'Over allocation of assets in the escrow'
export const ERR_CONTROLLED_ADDRESS_MUST_BE_ESCROW = 'Controlled address must be escrow'