export const ERR_STAKE_KEY_REQUIRED = 'Stake key required'
export const ERR_RATE_MUST_BE_GREATER_THAN_ZERO = 'Rate must be greater than zero'
export const ERR_RATE_MUST_BE_GREATER_THAN_WINNER_COUNT = 'Rate must be greater than winner count'
export const ERR_MAX_ENTRIES_CANNOT_BE_GREATER_THAN_RATE = 'Max entries cannot be greater than rate'
export const ERR_NOT_ENOUGH_FUNDS = 'Not enough funds'
export const ERR_NOT_READY_TO_DISBURSE = 'Not ready to disburse'
export const ERR_INVALID_DISBURSEMENT_PHASE = 'Invalid disbursement phase'
export const ERR_WINNING_TICKETS_ALREADY_EXIST = 'Winning tickets already exist'
export const ERR_INVALID_POOL_TYPE_FOR_CHECK = 'Invalid pool type for check'
export const ERR_DISBURSEMENT_NOT_READY_FOR_FINALIZATION = 'Disbursement not ready for finalization'
export const ERR_NOT_CREATOR = 'Not creator of the pool'

export const ERR_FORBIDDEN = 'Forbidden'
export const ERR_POOL_MUST_BE_DRAFT = 'Pool must be in draft status'
export const ERR_NOT_ALGO = 'Must be an Algo asset'
export const ERR_MUST_BE_ASA = 'Must be an ASA'
export const ERR_DAO_NOT_OPTED_IN = 'DAO not opted in to the asset'