export const ERR_ADMIN_CANNOT_BE_CONTROLLED = 'Admin and controlled address cannot be the same'
export const ERR_BAD_DEPLOYER = 'This contract must be deployed from a factory'
export const ERR_ONLY_ADMIN_CAN_UPDATE = 'Only an admin can update the application'
export const ERR_ONLY_ADMIN_CAN_CHANGE_REVOKE = 'Only an admin can change the revocation app'
export const ERR_ONLY_ADMIN_CAN_CHANGE_ADMIN = 'Only an admin can change the admin account'
export const ERR_ONLY_ADMIN_CAN_REKEY = 'Only an admin can rekey the account'
export const ERR_ONLY_ADMIN_CAN_ADD_PLUGIN = 'Only an admin can add a plugin'
export const ERR_ONLY_ADMIN_CAN_ADD_METHOD_RESTRICTION = 'Only an admin can add a method restriction'
export const ERR_ONLY_ADMIN_CAN_CHANGE_NICKNAME = 'Only an admin can change the nickname'
export const ERR_DOES_NOT_HOLD_ASSET = 'The account does not hold the asset'
export const ERR_NAMED_PLUGIN_ALREADY_EXISTS = 'A plugin with this name already exists'
export const ERR_ONLY_ADMIN_OR_REVOCATION_APP_CAN_REMOVE_PLUGIN = 'Only an admin or revocation app can remove plugins'
export const ERR_ONLY_ADMIN_OR_REVOCATION_APP_CAN_REMOVE_METHOD_RESTRICTION =
    'Only an admin or revocation app can remove method restrictions'
export const ERR_ONLY_ADMIN_OR_REVOCATION_APP_CAN_REMOVE_ALLOWANCE = 'Only an admin or revocation app can remove allowances'
export const ERR_SENDER_NOT_ALLOWED_TO_CALL_PLUGIN = 'This sender is not allowed to trigger this plugin'
export const ERR_PLUGIN_DOES_NOT_CONTROL_WALLET = 'This plugin is not in control of the account'
export const ERR_PLUGIN_DOES_NOT_HAVE_ADMIN_PRIVILEGES = 'This plugin does not have admin privileges'
export const ERR_DOMAIN_MUST_BE_LONGER_THAN_ZERO = 'Domain must not be length 0'
export const ERR_BAD_EXECUTION_KEY = 'The execution key does not match the group ID of the transaction'
export const ERR_PLUGIN_DOES_NOT_EXIST = 'Plugin does not exist'
export const ERR_METHOD_DOES_NOT_EXIST = 'Method does not exist'
export const ERR_METHOD_ALREADY_EXISTS = 'Method already exists'


export const ERR_ONLY_CREATOR_CAN_REKEY = 'only the creator can rekey a spend contract'
export const ERR_SENDER_MUST_BE_ADMIN_OR_CONTROLLED_ADDRESS = 'sender must be either controlledAddress or admin'
export const ERR_ADMIN_ONLY = 'admin only'
export const ERR_PLUGIN_EXPIRED = 'plugin expired'
export const ERR_PLUGIN_ON_COOLDOWN = 'plugin on cooldown'
export const ERR_INVALID_PLUGIN_CALL = 'invalid plugin call'
export const ERR_CANNOT_CALL_OTHER_APPS_DURING_REKEY = 'cannot call other apps during rekey'
export const ERR_INVALID_ONCOMPLETE = 'invalid oncomplete must be no op'
export const ERR_INVALID_SENDER_ARG = 'invalid sender must be this app id'
export const ERR_INVALID_SENDER_VALUE = 'invalid sender app id'
export const ERR_METHOD_ON_COOLDOWN = 'method on cooldown'
export const ERR_MISSING_REKEY_BACK = 'missing rekey back'
export const ERR_MALFORMED_OFFSETS = 'malformed method offsets'
export const ERR_INVALID_METHOD_SIGNATURE_LENGTH = 'invalid method signature length'
export const ERR_SENDER_MUST_BE_ADMIN_PLUGIN = 'sender must be admin plugin'
export const ERR_ZERO_ADDRESS_DELEGATION_TYPE = 'delegation type must not be self for global plugins'
export const ERR_ESCROW_REQUIRED_TO_BE_SET_AS_DEFAULT = 'escrow must be set if defaultToEscrow is true'
export const ERR_ALLOWANCE_ALREADY_EXISTS = 'allowance already exists'
export const ERR_ALLOWANCE_DOES_NOT_EXIST = 'allowance does not exist'
export const ERR_EXECUTION_KEY_ALREADY_EXISTS = 'execution key already exists'
export const ERR_EXECUTION_KEY_DOES_NOT_EXIST = 'execution key does not exist'

export const ERR_INVALID_PAYMENT = 'invalid payment'

export const ERR_ONLY_APPS = 'Only applications can create spending accounts'
export const ERR_FORBIDDEN = 'only the creator wallet can delete a spending account'

export const ERR_ESCROW_LOCKED = 'Escrow is locked'
export const ERR_ESCROW_ALREADY_EXISTS = 'Escrow already exists'
export const ERR_ESCROW_NAME_REQUIRED = 'Escrow name is required'
export const ERR_ESCROW_DOES_NOT_EXIST = 'Escrow does not exist'

export const ERR_ONLY_WALLET_OR_PLUGIN = 'Only the wallet or plugin can opt in'
export const ERR_ONLY_FACTORY_CAN_DELETE = 'Only the factory can delete the application'
export const ERR_ALLOWANCE_EXCEEDED = 'Allowance exceeded'